-- Kolom tambahan tabel bumdes untuk data CSV "Rekap data Keseluruhan BUM Desa".
--
-- WAJIB ada sebelum backend versi baru menyala: skema Prisma sudah menyebut
-- kolom-kolom ini, dan Prisma menuliskan seluruh nama kolom secara eksplisit
-- di setiap SELECT. Kalau kolomnya belum dibuat, semua query bumdes gagal
-- dengan error 1054. auto-migrate.js berjalan sebelum pm2 restart, jadi
-- urutannya aman.
--
-- Semua kolom NULL dan tidak mengubah data yang sudah ada.
-- Diturunkan dari scripts/bumdes-import/mapping.js (74 kolom).

ALTER TABLE `bumdes`
  ADD COLUMN `Status2024` VARCHAR(20) NULL,
  ADD COLUMN `KeteranganTidakAktif2024` VARCHAR(20) NULL,
  ADD COLUMN `Pemeringkatan2022` VARCHAR(30) NULL,
  ADD COLUMN `NilaiPemeringkatan2022` VARCHAR(10) NULL,
  ADD COLUMN `Pemeringkatan2023` VARCHAR(30) NULL,
  ADD COLUMN `NilaiPemeringkatan2023` VARCHAR(10) NULL,
  ADD COLUMN `Pemeringkatan2024` VARCHAR(30) NULL,
  ADD COLUMN `KetPemeringkatan2024` VARCHAR(10) NULL,
  ADD COLUMN `Pemeringkatan2024Sem1` VARCHAR(30) NULL,
  ADD COLUMN `PemeringkatanApp2023` VARCHAR(30) NULL,
  ADD COLUMN `EvaluasiRPJMN2024` VARCHAR(30) NULL,
  ADD COLUMN `PemeringkatanApp2024` VARCHAR(30) NULL,
  ADD COLUMN `Pemeringkatan2026` VARCHAR(30) NULL,
  ADD COLUMN `StatusBadanHukum2026` VARCHAR(60) NULL,
  ADD COLUMN `StatusBadanHukum2026Feb` VARCHAR(60) NULL,
  ADD COLUMN `StatusBadanHukum2025Pembinaan` VARCHAR(60) NULL,
  ADD COLUMN `StatusBadanHukum2025` VARCHAR(60) NULL,
  ADD COLUMN `StatusBadanHukum2024` VARCHAR(60) NULL,
  ADD COLUMN `StatusBadanHukum2023` VARCHAR(60) NULL,
  ADD COLUMN `StatusBadanHukum2022` VARCHAR(60) NULL,
  ADD COLUMN `NamaStafLainnya` VARCHAR(255) NULL,
  ADD COLUMN `JenisKelaminStafLainnya` VARCHAR(20) NULL,
  ADD COLUMN `HPStafLainnya` VARCHAR(50) NULL,
  ADD COLUMN `JenisUsaha2021` TEXT NULL,
  ADD COLUMN `JenisUsahaKetahananPangan` TEXT NULL,
  ADD COLUMN `KeteranganUsahaKetahananPangan` TEXT NULL,
  ADD COLUMN `VolumeKetahananPangan` TEXT NULL,
  ADD COLUMN `AnggaranModalKetahananPangan` DECIMAL(15,2) NULL,
  ADD COLUMN `Omset2024Sem1` DECIMAL(15,2) NULL,
  ADD COLUMN `Laba2024Sem1` DECIMAL(15,2) NULL,
  ADD COLUMN `Omset2025` DECIMAL(15,2) NULL,
  ADD COLUMN `Laba2025` DECIMAL(15,2) NULL,
  ADD COLUMN `PenganggaranPenyertaanModal2025` DECIMAL(15,2) NULL,
  ADD COLUMN `PenyertaanModalTPKK` DECIMAL(15,2) NULL,
  ADD COLUMN `TotalRealisasiPenyertaanModal20192025` DECIMAL(15,2) NULL,
  ADD COLUMN `JumlahModalAwal` DECIMAL(15,2) NULL,
  ADD COLUMN `KontribusiTerhadapPADes2025` DECIMAL(15,2) NULL,
  ADD COLUMN `KontribusiKemitraanPADes2024` DECIMAL(15,2) NULL,
  ADD COLUMN `KontribusiKemitraanPADes2025` DECIMAL(15,2) NULL,
  ADD COLUMN `DesaWisataStatus` VARCHAR(20) NULL,
  ADD COLUMN `PeranMBG` TEXT NULL,
  ADD COLUMN `MekanismeKerjaSamaMBG` TEXT NULL,
  ADD COLUMN `JumlahSPPG` INT NULL,
  ADD COLUMN `TahunKerjaSamaMBG` VARCHAR(20) NULL,
  ADD COLUMN `BantuanLainnya` TEXT NULL,
  ADD COLUMN `Pelatihan2022` TEXT NULL,
  ADD COLUMN `Pelatihan2023` TEXT NULL,
  ADD COLUMN `PelatihanBUMDesa2024` TEXT NULL,
  ADD COLUMN `PelatihanPenasehatPengawas2024` TEXT NULL,
  ADD COLUMN `Pelatihan2025Pertama` TEXT NULL,
  ADD COLUMN `PelatihanBusinessPlanUI2023` TEXT NULL,
  ADD COLUMN `SABISA` TEXT NULL,
  ADD COLUMN `FGDUI2024` TEXT NULL,
  ADD COLUMN `FGDBRIN2024` TEXT NULL,
  ADD COLUMN `ToTSTAN` TEXT NULL,
  ADD COLUMN `SosialisasiELearningUI` TEXT NULL,
  ADD COLUMN `PesertaPelatihanBalaiBesarKemendesa` TEXT NULL,
  ADD COLUMN `Pembinaan2022` TEXT NULL,
  ADD COLUMN `Pembinaan2023` TEXT NULL,
  ADD COLUMN `Pembinaan2024` TEXT NULL,
  ADD COLUMN `ProgressHasilPembinaan2024` TEXT NULL,
  ADD COLUMN `DeskPendataan2025` VARCHAR(20) NULL,
  ADD COLUMN `KehadiranDesk2026` VARCHAR(20) NULL,
  ADD COLUMN `PermintaanDataKPK` TEXT NULL,
  ADD COLUMN `MasalahPendirianPenyertaanModal` TEXT NULL,
  ADD COLUMN `TahunPenyertaanModalBermasalah` TEXT NULL,
  ADD COLUMN `SuratKonfirmasi` TEXT NULL,
  ADD COLUMN `BerkasSurat` TEXT NULL,
  ADD COLUMN `PermasalahanLainnya` TEXT NULL,
  ADD COLUMN `ECommerce` TEXT NULL,
  ADD COLUMN `LinkSK` TEXT NULL,
  ADD COLUMN `LinkLapKeuangan2021` TEXT NULL,
  ADD COLUMN `LinkSKKepengurusan2021` TEXT NULL,
  ADD COLUMN `CatatanTambahan` TEXT NULL;
